AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla Funcion Intrínseca

# Recursos
Resources:
    MyS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-${AWS::StackName}" 

            # Le estoy diciendo que sustituya lo de las llaves por su valor con !Sub