AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla SecurityGroup/InstanciaEC2"

# Recursos
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir trafico SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      KeyName: vockey
      SecurityGroups:
        - !Ref MySecurityGroup
      ImageId: ami-09115b7bffbe3c5e4


