AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla SecurityGroup"

# Recursos
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Tráfico SSH
      GroupName: SecurityGroupSSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0