AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla SSH Security Group

# Recursos
Resources:
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow SSH & HTTP access to client
        GroupName: SSH-HTTP-SecurityGroup
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
